mix 1/2 cup maida , 6tbsp powdered sugar , 2tbsp cocoa powder , 1/2tsp baking powder , 
1/8tsp baking soda in a bowl and add milk slowly and when the batter consists lump add
oil.now add vinger or lemon juice and stir it for 10 to 15 minutes and after that pour 
the batter into the cake mold and at last use chocholate ganache after you pour the
batter put a little batter on the top of the chocolate ganache now at last preheat 
the otg /convection at 180 degree for 10 minutes and bake it for 5-6 minutes and for 
microwave at high power for 1 minute and 30 sec. it is very spongy and turned out of lava.

                     "enjoy your chocho lava cake"
